- 1.1.9
- _NAME: MX Master 3S
  _absent: [hi-res-scroll, lowres-scroll-mode, onboard_profiles, report_rate, pointer_speed, speed-change, backlight, backlight-timed, fn-swap, persistent-remappable-keys,
    disable-keyboard-keys, crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led, multiplatform, gesture2-gestures, gesture2-divert, gesture2-params,
    sidetone, equalizer, adc_power_management]
  _battery: 4100
  _modelId: B03400000000
  _sensitive: {divert-keys: true, dpi: true, hires-scroll-mode: false, hires-smooth-resolution: true, reprogrammable-keys: false, scroll-ratchet: false,
    smart-shift: false, thumb-scroll-invert: true, thumb-scroll-mode: true}
  _serial: 3B64584F
  _unitId: 3B64584F
  _wpid: B034
  change-host: null
  divert-keys: {82: 0, 83: 2, 86: 1, 195: 1, 196: 0}
  dpi: 1200
  hires-scroll-mode: false
  hires-smooth-invert: false
  hires-smooth-resolution: false
  reprogrammable-keys: {80: 80, 81: 81, 82: 82, 83: 83, 86: 86, 195: 195, 196: 196}
  scroll-ratchet: 2
  smart-shift: 10
  thumb-scroll-invert: true
  thumb-scroll-mode: false
- _NAME: MX Anywhere 3
  _absent: [hi-res-scroll, lowres-scroll-mode, scroll-ratchet, thumb-scroll-invert, thumb-scroll-mode, onboard_profiles, report_rate, pointer_speed, speed-change,
    backlight, backlight-timed, fn-swap, persistent-remappable-keys, disable-keyboard-keys, crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led,
    multiplatform, gesture2-gestures, gesture2-divert, gesture2-params, sidetone, equalizer, adc_power_management]
  _battery: 4100
  _modelId: B02D00000000
  _sensitive: {divert-keys: true, dpi: true, smart-shift: true}
  _serial: BE66BA8E
  _unitId: BE66BA8E
  _wpid: B02D
  change-host: null
  divert-keys: {82: 0, 83: 2, 86: 0, 196: 0}
  dpi: 1200
  hires-scroll-mode: false
  hires-smooth-invert: false
  hires-smooth-resolution: false
  reprogrammable-keys: {80: 80, 81: 81, 82: 82, 83: 83, 86: 86, 196: 196}
  smart-shift: 5
