- 1.1.11
- _NAME: MX Master 3S
  _absent: [hi-res-scroll, lowres-scroll-mode, onboard_profiles, report_rate, report_rate_extended, pointer_speed, speed-change, backlight, backlight_level,
    backlight_duration_hands_out, backlight_duration_hands_in, backlight_duration_powered, backlight-timed, led_control, led_zone_, fn-swap, persistent-remappable-keys,
    disable-keyboard-keys, crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led, multiplatform, gesture2-gestures, gesture2-divert, gesture2-params,
    sidetone, equalizer, adc_power_management]
  _battery: 0x1004
  _modelId: B03400000000
  _sensitive: {divert-keys: true, dpi: true, hires-scroll-mode: false, hires-smooth-resolution: true, reprogrammable-keys: false, scroll-ratchet: false,
    smart-shift: false, thumb-scroll-invert: true, thumb-scroll-mode: true}
  _serial: 3B64584F
  _unitId: 3B64584F
  _wpid: B034
  change-host: null
  divert-keys: {0x52: 0x0, 0x53: 0x2, 0x56: 0x1, 0xc3: 0x1, 0xc4: 0x0}
  dpi: 0x4b0
  hires-scroll-mode: false
  hires-smooth-invert: false
  hires-smooth-resolution: false
  reprogrammable-keys: {0x50: 0x50, 0x51: 0x51, 0x52: 0x52, 0x53: 0x53, 0x56: 0x56, 0xc3: 0xc3, 0xc4: 0xc4}
  scroll-ratchet: 0x2
  smart-shift: 0xa
  thumb-scroll-invert: true
  thumb-scroll-mode: false
- _NAME: MX Anywhere 3
  _modelId: B02D00000000
  _sensitive: {divert-keys: true, dpi: true, smart-shift: true}
  _serial: BE66BA8E
  _unitId: BE66BA8E
  _wpid: B02D
  change-host: null
  divert-keys: {0x52: 0x0, 0x53: 0x2, 0x56: 0x0, 0xc4: 0x0}
  dpi: 0x4b0
  hires-scroll-mode: false
  hires-smooth-invert: false
  hires-smooth-resolution: false
  reprogrammable-keys: {0x50: 0x50, 0x51: 0x51, 0x52: 0x52, 0x53: 0x53, 0x56: 0x56, 0xc4: 0xc4}
  smart-shift: 0x5
- _NAME: Illuminated Living-Room Keyboard K830
  _modelId: B335404C0000
  _sensitive: {hires-scroll-mode: ignore, hires-smooth-invert: ignore, hires-smooth-resolution: ignore}
  _serial: 3FF6CB53
  _unitId: 4361D7E3
  _wpid: 404C
  disable-keyboard-keys: {0x1: false, 0x4: false, 0x8: false, 0x10: false}
  divert-keys: {0x1: 0x0, 0x2: 0x0, 0x3: 0x0, 0x4: 0x0, 0x5: 0x0, 0x6: 0x0, 0x8: 0x0, 0x22: 0x0, 0x28: 0x0, 0x3e: 0x0, 0x40: 0x0, 0x4f: 0x0, 0x54: 0x0,
    0x6e: 0x0, 0x91: 0x0, 0xb7: 0x0, 0xb8: 0x0}
  fn-swap: true
  gesture2-divert: {0x1: false, 0x2: false, 0xa: false, 0x2c: false, 0x40: false, 0x41: false, 0x43: false, 0x54: false, 0x55: false, 0x64: false}
  gesture2-gestures: {0x1: true, 0x2: true, 0xa: true, 0x1e: true, 0x22: false, 0x2a: true, 0x2b: true, 0x2d: false, 0x40: false, 0x41: false, 0x43: false,
    0x54: true}
  gesture2-params:
    0x4: {scale: 0x100}
- _NAME: MX Master 3S
  _sensitive: {hires-scroll-mode: ignore, hires-smooth-invert: ignore, hires-smooth-resolution: ignore}
  _wpid: B034
